Functions

In [1]:
import re
import numpy as np

indices = {}


def load(name):
    """
    Load the data

    params:
    name:   file directory and name
    """
    arr = []
    with open(name) as f:
        for i in f:
            x = [j.strip() for j in re.split(',|\[|\]', i)]
            xtmp = []
            xtmp.append(int(x[1]))
            xtmp.append(int(x[2]))
            xtmp2 = []
            xtmp2.append(int(x[4]))
            xtmp2.append(int(x[5]))
            arr.append(xtmp)
            arr.append(xtmp2)

    return arr


# textArr.sort(key=takeSecond)
def takeThird(arr):
    """
    Used as a key to return the 2nd element in an array

    params:
    arr:    input array
    """
    return arr[2]


def dist(a, b):
    return np.sqrt(np.sum((a-b)**2))


def dist_2(x, y):
    x1 = x[0]
    x2 = x[1]
    y1 = y[0]
    y2 = y[1]
    return ((x1 - y1)**2 + (x2 - y2)**2)**0.5
    

def pairwise_distances(myArray):
    # Set negative values to zero
    myArray[myArray < 0] = 0
    d = np.sqrt(np.sum((myArray[:, np.newaxis, :] - myArray[np.newaxis, :, :])**2, axis=-1))
    return d


def buildSet(arr):
    my_set = set()
    my_keys = []
    c = 0
    for i in arr:
        x = (i[0], i[1])
        if x not in my_set:
            my_set.add((i[0], i[1]))
            my_keys.append(c)
            c += 1
    l = list(my_set)
    return l, my_keys


def create_map(lst):
    indices = {}
    for i, x in enumerate(lst):
        indices[x] = i
    return indices


def find_index(element):
    return indices[element]

Class

In [2]:
# Credit to: https://www.programiz.com/dsa/kruskal-algorithm
class Graph:
    def __init__(self, vertices, edge):
        self.V = vertices
        self.graph = edge
        self.i = 0

    def get(self):
        return self.graph

    # Search function
    def find(self, parent, i):
        if parent[i] == i:
            return i
        return self.find(parent, parent[i])

    def apply_union(self, parent, rank, x, y):
        xroot = self.find(parent, x)
        yroot = self.find(parent, y)
        if rank[xroot] < rank[yroot]:
            parent[xroot] = yroot
        elif rank[xroot] > rank[yroot]:
            parent[yroot] = xroot
        else:
            parent[yroot] = xroot
            rank[xroot] += 1

    #  Applying Kruskal algorithm
    def kruskal_algo(self, initial_edges):
        result = initial_edges[:]
        i, e = 0, len(initial_edges)
        self.graph = sorted(self.graph, key=lambda item: item[2])
        parent = []
        rank = []
        total = 0
        for node in range(self.V):
            parent.append(node)
            rank.append(0)
        for k in result:
            u = k[0]
            v = k[1]
            w = k[2]
            x = self.find(parent, u)
            y = self.find(parent, v)
            self.apply_union(parent, rank, x, y)
        while e < self.V - 1:
            u, v, w = self.graph[i]
            i = i + 1
            x = self.find(parent, u)
            y = self.find(parent, v)
            if x != y:
                e = e + 1
                result.append([u, v, w])
                self.apply_union(parent, rank, x, y)
                total += w
        # for u, v, weight in result:
            # print("%d - %d: %d" % (u, v, weight))
        print("Total = ", total)

Load

In [3]:
arr = load("./graph_2.txt")

Keys

In [4]:
myList, myKeys = buildSet(arr)
num_vertices = len(myList)
num_edges = int((num_vertices * (num_vertices - 1)) / 2)

Indices

In [5]:
indices = create_map(myList)

Test

Initial Edges

In [6]:
initial_edges = []
for i in range(0, len(arr), 2):
    initial_edges.append([find_index((arr[i][0], arr[i][1])), find_index((arr[i + 1][0], arr[i + 1][1])), dist_2(arr[i], arr[i + 1])])

In [7]:
# Convert myList to numpy array
myArray = np.array(myList)
# myArray = myArray.astype(int)

# Compute pairwise distances using vectorized operations
d = pairwise_distances(myArray)


C:\Users\janhr\AppData\Local\Temp\ipykernel_3832\1701954911.py:56: RuntimeWarning: invalid value encountered in sqrt
  d = np.sqrt(np.sum((myArray[:, np.newaxis, :] - myArray[np.newaxis, :, :])**2, axis=-1))


In [8]:
# Generate edges using numpy operations
ii,jj = np.triu_indices(len(myArray), k=1)
e = np.column_stack([ii,jj,d[ii,jj]])

In [10]:
# Sort edges by weight
e = e[e[:,2].argsort()]
print(e)

[[4.331e+03 7.046e+03 1.000e+00]
 [2.485e+03 4.657e+03 1.000e+00]
 [3.311e+03 6.693e+03 1.000e+00]
 ...
 [2.546e+03 6.626e+03       nan]
 [2.546e+03 6.835e+03       nan]
 [9.855e+03 9.856e+03       nan]]


In [ ]:
# Add edges to graph
g = Graph(num_vertices, e)

All edges

In [96]:
# e = [[find_index(myList[i]), find_index(myList[j]), dist(myList[i], myList[j])] for i in range(len(myList)) for j in range(i + 1, len(myList))]

Add edges

In [97]:
# e.sort(key=takeThird)
# for i in e:
#     g.add_edge(i[0], i[1], i[2])

Algorithm

In [98]:
g.kruskal_algo(initial_edges)